version: '3.8'

services:
  app:
    image: guiindiciate/springboot-images-rotasdereciclagem:latest
    container_name: springboot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:xe
      SPRING_DATASOURCE_USERNAME: rm97784
      SPRING_DATASOURCE_PASSWORD: 081100
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_FLYWAY_URL: jdbc:oracle:thin:@oracle-db:1521:xe
      SPRING_FLYWAY_USER: rm97784
      SPRING_FLYWAY_PASSWORD: 081100
    depends_on:
      - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle_db
    environment:
      ORACLE_PASSWORD: 081100
      ORACLE_DATABASE: ORCL
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
