CREATE SEQUENCE SEQ_CAMINHOES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CAMINHOES (
    id_caminhao INTEGER DEFAULT SEQ_CAMINHOES.NEXTVAL NOT NULL PRIMARY KEY,
    motorista VARCHAR(200) NOT NULL,
    modelo VARCHAR2(50) NOT NULL,
    placa VARCHAR2(7) NOT NULL,
    capacidade_litros INTEGER NOT NULL
);