CREATE SEQUENCE SEQ_CAMINHOES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CAMINHOES (
    id_caminhao INTEGER DEFAULT SEQ_CAMINHOES.NEXTVAL NOT NULL PRIMARY KEY,
    motorista VARCHAR(200) NOT NULL,
    modelo VARCHAR2(50) NOT NULL,
    placa VARCHAR2(7) NOT NULL,
    capacidade_litros INTEGER NOT NULL
);

CREATE SEQUENCE SEQ_MORADORES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_MORADORES (
    id_morador INTEGER DEFAULT SEQ_MORADORES.NEXTVAL NOT NULL PRIMARY KEY,
    nome VARCHAR2(200) NOT NULL,
    endereco VARCHAR2(200) NOT NULL,
    end_numero INTEGER NOT NULL,
    end_complemento VARCHAR2(60),
    end_bairro VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(12) NOT NULL
);

CREATE SEQUENCE SEQ_AGENDAMENTOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE AGENDAMENTOS (
    id_agendamento INTEGER DEFAULT SEQ_AGENDAMENTOS.NEXTVAL NOT NULL PRIMARY KEY,
    data DATE NOT NULL,
    tipo_residuo VARCHAR2(100),
    quantidade_litros INTEGER NOT NULL,
    status VARCHAR2(60) NOT NULL,
    id_caminhao INTEGER NOT NULL,
    id_morador INTEGER NOT NULL,
    CONSTRAINT fk_agendamento_caminhao FOREIGN KEY (id_caminhao) REFERENCES TBL_CAMINHOES (id_caminhao),
    CONSTRAINT fk_agendamento_morador FOREIGN KEY (id_morador) REFERENCES TBL_MORADORES (id_morador)
);

CREATE SEQUENCE SEQ_ROTAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE ROTAS (
    id_rota INTEGER DEFAULT SEQ_ROTAS.NEXTVAL NOT NULL PRIMARY KEY,
    pontos_de_coleta VARCHAR2(1200) NOT NULL,
    horario_inicial DATE NOT NULL,
    horario_final DATE NOT NULL,
    id_caminhao INTEGER NOT NULL,
    CONSTRAINT fk_rota_caminhao FOREIGN KEY (id_caminhao) REFERENCES TBL_CAMINHOES (id_caminhao)
);

CREATE SEQUENCE SEQ_NOTIFICACOES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE NOTIFICACOES (
    id_notificacao INTEGER DEFAULT SEQ_NOTIFICACOES.NEXTVAL NOT NULL PRIMARY KEY,
    mensagem VARCHAR2(100) NOT NULL,
    data_envio DATE NOT NULL,
    status VARCHAR2(60) NOT NULL,
    id_morador INTEGER NOT NULL,
    CONSTRAINT fk_notificacao_morador FOREIGN KEY (id_morador) REFERENCES TBL_MORADORES (id_morador)
);
