CREATE SEQUENCE SEQ_MORADORES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_MORADORES (
    id_morador INTEGER DEFAULT SEQ_MORADORES.NEXTVAL NOT NULL PRIMARY KEY,
    nome VARCHAR2(200) NOT NULL,
    endereco VARCHAR2(200) NOT NULL,
    end_numero INTEGER NOT NULL,
    end_complemento VARCHAR2(60),
    end_bairro VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(12) NOT NULL
);
