CREATE SEQUENCE SEQ_NOTIFICACOES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE NOTIFICACOES (
    id_notificacao INTEGER DEFAULT SEQ_NOTIFICACOES.NEXTVAL NOT NULL PRIMARY KEY,
    mensagem VARCHAR2(100) NOT NULL,
    data_envio DATE NOT NULL,
    status VARCHAR2(60) NOT NULL,
    id_morador INTEGER NOT NULL,
    CONSTRAINT fk_notificacao_morador FOREIGN KEY (id_morador) REFERENCES TBL_MORADORES (id_morador)
);
